Repository Damborghinii/Damborghinii-Client, pull requests merged in 2025-06, with the labels that each got.

#6 Feature/#5 BottomNavBar, BottomSheet, Button 공용 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/icons/adjustment_management.svg
  src/assets/icons/close.svg
  src/assets/icons/contract.svg
  src/assets/icons/index.ts
  src/assets/icons/investment_arrow.svg
  src/assets/icons/my_nft.svg
  src/components/common/bottomNavBar/BottomNavBar.stories.tsx
  src/components/common/bottomNavBar/BottomNavBar.tsx
  src/components/common/bottomSheet/BottomSheet.stories.tsx
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/button/Button.stories.tsx
  src/components/common/button/Button.tsx
  src/layouts/DefaultLayout.tsx
  src/pages/adjustment/AdjustmentPage.tsx
  src/pages/contract/ContractPage.tsx
  src/pages/investment/InvestmentPage.tsx
  src/pages/myNft/MyNftPage.tsx
  src/routes/router.tsx
  src/styles/theme.ts
  src/types/svg.d.ts
  src/vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: 지호, ✨ Feature

#25 [Feature] #22 - 정산관리 플로우 구현
  src/assets/svg/IcArrowRight.tsx
  src/assets/svg/IcMoney.tsx
  src/assets/svg/index.ts
  src/components/common/horizontalDivider/HorizontalDivider.tsx
  src/pages/_hooks/useTabBar.ts
  src/pages/adjustment/AdjustmentPage.tsx
  src/pages/adjustment/_components/AdjustmentCard.tsx
  src/pages/adjustment/_components/AdjustmentTabBar.tsx
  src/pages/adjustment/_components/BottomSection.tsx
  src/pages/adjustment/containers/Adjustment.tsx
  src/pages/adjustment/containers/AdjustmentGiving.tsx
  src/pages/adjustment/containers/AdjustmentReceived.tsx
  src/routes/router.tsx
  yarn.lock
Labels: 세호, ✨ Feature

#32 fix
  src/components/common/bottomNavBar/BottomNavBar.tsx
  src/pages/invesetment/_components/PawnCard.tsx
  src/pages/invesetment/_components/Text.ts
  src/pages/main/MainPage.tsx
  src/pages/main/_components/MainTitle.tsx
  src/pages/main/_hooks/getSelectedType.ts
  src/pages/myNft/MyNft.styled.ts
  src/pages/myNft/MyNftPage.tsx
  src/pages/myNft/_components/nftRegister/NftRegister.styled.ts
  src/pages/myNft/pages/NftCard.tsx
  src/styles/global.ts
Labels: 세호, 🐞 Fix

#39 [Feature] #33 각종 API 연결
  src/apis/adjustment.ts
  src/apis/axios.ts
  src/apis/investment.ts
  src/apis/loan.ts
  src/apis/myNft.ts
  src/pages/_hooks/useTabBar.ts
  src/pages/adjustment/_components/AdjustmentCard.tsx
  src/pages/adjustment/_components/AdjustmentTabBar.tsx
  src/pages/adjustment/_components/BottomSection.tsx
  src/pages/adjustment/containers/AdjustmentGiving.tsx
  src/pages/adjustment/containers/AdjustmentReceived.tsx
  src/pages/invesetment/InvestmentInfo.tsx
  src/pages/invesetment/InvestmentInfoInput.tsx
  src/pages/invesetment/_components/PawnCard.tsx
  src/pages/invesetment/_components/ProgressRateSection.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/_components/MainLoanCard.tsx
  src/pages/main/_components/MainTitle.tsx
  src/pages/main/_components/NftCard.tsx
  src/pages/myNft/MyNftPage.tsx
  src/pages/myNft/_components/NoticeSection.tsx
  src/pages/myNft/_components/nftStatusList/NftStatusList.tsx
  src/pages/myNft/_hooks/useNftStatusList.ts
  src/pages/myNft/pages/LoanApply.tsx
  src/pages/myNft/pages/LoanConfirm.tsx
  src/pages/myNft/pages/LoanInfoInput.tsx
  src/routes/router.tsx
  yarn.lock
Labels: 세호, ✨ Feature

#43 fix/#41: NFT detail page 추가구현
  src/apis/nft.ts
  src/constants/path.ts
  src/pages/main/_components/NftCard.tsx
  src/pages/myNft/pages/NftDetailPage.tsx
  src/routes/router.tsx
  yarn.lock
Labels: 지호, 🐞 Fix
