Repository Damborghinii/Damborghinii-Client, pull requests merged in 2025-08, with the labels that each got.

#48 [Setting] #47 디자인 시스템 수정
  src/components/common/button/Button.tsx
  src/styles/theme.ts
Labels: 지호, ⚙️ Setting

#50 [Feature] #49 로그인, 회원가입 뷰 리디자인
  src/assets/icons/denied_icon.svg
  src/assets/icons/index.ts
  src/components/common/input/SingleInputSection.tsx
  src/pages/login/LoginPage.tsx
  src/pages/signUp/SignUpPage1.tsx
  src/pages/signUp/SignUpPage3.tsx
  src/pages/signUp/SignUpPage4.tsx
Labels: 지호, ✨ Feature

#59 [Feature] #56 내 음원 뷰 리디자인 반영
  src/assets/icons/adjustment_management.svg
  src/assets/icons/my_nft.svg
  src/components/common/button/Button.tsx
  src/components/common/mainBadge/MainBadge.tsx
  src/pages/main/_components/MainLoanCard.tsx
  src/pages/myNft/MyNft.styled.ts
  src/pages/myNft/MyNftPage.tsx
  src/pages/myNft/_components/musicCard/MusicCard.styled.ts
  src/pages/myNft/_components/musicCard/MusicCard.tsx
  src/pages/myNft/_components/nftRegister/NftRegister.styled.ts
  src/pages/myNft/_components/nftRegister/NftRegister.tsx
  src/pages/myNft/_components/nftStatusList/NftStatusList.tsx
  src/pages/myNft/_hooks/useNftStatusList.ts
Labels: 세호, ✨ Feature

#61 [Refactor] #60 정산관리 리팩토링
  index.html
  public/logo.png
  public/logo.svg
  src/components/common/bottomNavBar/BottomNavBar.tsx
  src/contexts/NftFormContext.tsx
  src/layouts/DefaultLayout.tsx
  src/pages/adjustment/_components/AdjustmentCard.tsx
  src/pages/adjustment/containers/Adjustment.tsx
  src/pages/adjustment/containers/AdjustmentGiving.tsx
  src/pages/adjustment/containers/AdjustmentReceived.tsx
  src/pages/main/MainPage.tsx
  src/pages/myNft/MyNftPage.tsx
Labels: 세호, ✨ Feature

#62 [feature] my Nft 상세 페이지 구현
  src/App.tsx
  src/assets/icons/index.ts
  src/assets/icons/wallet.svg
  src/components/common/bottomNavBar/BottomNavBar.tsx
  src/components/common/topBar/SubTopBar.tsx
  src/components/common/topBar/TopBar.tsx
  src/contexts/AuthContext.tsx
  src/layouts/DefaultLayout.tsx
  src/layouts/NoBottomBarLayout.tsx
  src/layouts/RootWrapper.tsx
  src/pages/login/LoginPage.tsx
  src/pages/main/_components/BadgeScroll.tsx
  src/pages/menu/MenuPage.tsx
  src/pages/myNft/MyNftDetailPage.tsx
  src/pages/myNft/MyNftPage.tsx
  src/pages/myNft/_components/ConfirmNoticeSection.tsx
  src/pages/myNft/_components/NoticeSection.tsx
  src/pages/myNft/_components/PriceInputSection.tsx
  src/pages/myNft/pages/LoanInfoInput.tsx
  src/routes/router.tsx
Labels: 지호, ✨ Feature

#65 [Feature] #64: main api 연결
  index.html
  src/apis/getMain.ts
  src/pages/main/MainPage.tsx
  src/pages/main/_components/BadgeScroll.tsx
  src/pages/main/_components/NewLoanCard.tsx
Labels: 세호, ✨ Feature

#71 [feature] 내가 발행한 nft 투자하기 api 연결
  src/apis/loan.ts
  src/constants/path.ts
  src/hooks/queries/useLoanInfo.ts
  src/hooks/queries/useMyNftDetail.ts
  src/layouts/NoBottomBarLayout.tsx
  src/pages/myNft/MyNftDetailPage.tsx
  src/pages/myNft/MyNftPage.tsx
  src/pages/myNft/_components/ConfirmNoticeSection.tsx
  src/pages/myNft/_components/musicCard/MusicCard.tsx
  src/pages/myNft/pages/LoanConfirm.tsx
  src/pages/myNft/pages/LoanInfoInput.tsx
  src/routes/router.tsx
Labels: 지호, ✨ Feature

#74 [feature] 계약서 작성 api 연결
  src/apis/loan.ts
  src/constants/path.ts
  src/hooks/queries/useLoanAgreement.ts
  src/hooks/queries/useSubmitLoan.ts
  src/pages/myNft/_components/myNftContract/ContractCondition.tsx
  src/pages/myNft/_components/myNftContract/ContractNftInfoSection.tsx
  src/pages/myNft/_components/myNftContract/ContractSign.tsx
  src/pages/myNft/pages/LoanConfirm.tsx
  src/pages/myNft/pages/MyNftContract.tsx
Labels: 지호, ✨ Feature

#76 [feature] 투자하기 api 수정
  src/apis/investment.ts
  src/hooks/queries/useInvestContract.ts
  src/pages/adjustment/containers/AdjustmentGiving.tsx
  src/pages/adjustment/containers/AdjustmentReceived.tsx
  src/pages/main/MusicApplyPage.tsx
  src/pages/myNft/_components/myNftContract/SignContainer.tsx
Labels: 지호, ✨ Feature
